# Generated by Django 5.1.1 on 2024-10-08 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Breed')),
                ('hairines', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hairines')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='users.usermodel', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Cat',
                'verbose_name_plural': 'Cats',
            },
        ),
    ]
